quote_data = (
    (
        "Be yourself; everyone else is already taken.",
        "Oscar Wilde",
        "Irish poet",
        "Inspirational",
    ),
    (
        "Be yourself; everyone else is already taken.",
        "Oscar Wilde",
        "Irish poet",
        "Advice",
    ),
    (
        "Be yourself; everyone else is already taken.",
        "Oscar Wilde",
        "Irish poet",
        "Humor",
    ),
    (
        "To live is the rarest thing in the world. Most people exist, that is all.",
        "Oscar Wilde",
        "Irish poet",
        "Philosophy",
    ),
    (
        "To live is the rarest thing in the world. Most people exist, that is all.",
        "Oscar Wilde",
        "Irish poet",
        "Humor",
    ),
    ("True friends stab you in the front.", "Oscar Wilde", "Irish poet", "Philosophy"),
    ("True friends stab you in the front.", "Oscar Wilde", "Irish poet", "People"),
    (
        "Women are made to be Loved, not understood.",
        "Oscar Wilde",
        "Irish poet",
        "Philosophy",
    ),
    (
        "Women are made to be Loved, not understood.",
        "Oscar Wilde",
        "Irish poet",
        "Humor",
    ),
    (
        "Be the change that you wish to see in the world.",
        "Mahatma Gandhi",
        "Indian leader",
        "Inspirational",
    ),
    (
        "Be the change that you wish to see in the world.",
        "Mahatma Gandhi",
        "Indian leader",
        "Philosophy",
    ),
    (
        "Be the change that you wish to see in the world.",
        "Mahatma Gandhi",
        "Indian leader",
        "Advice",
    ),
    (
        "Live as if you were to die tomorrow. Learn as if you were to live forever.",
        "Mahatma Gandhi",
        "Indian leader",
        "Inspirational",
    ),
    (
        "Live as if you were to die tomorrow. Learn as if you were to live forever.",
        "Mahatma Gandhi",
        "Indian leader",
        "Life",
    ),
    (
        "Live as if you were to die tomorrow. Learn as if you were to live forever.",
        "Mahatma Gandhi",
        "Indian leader",
        "Advice",
    ),
    (
        "No one can make you feel inferior without your consent.",
        "Eleanor Roosevelt",
        "Former First Lady of the United States",
        "Wisdom",
    ),
    (
        "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
        "Eleanor Roosevelt",
        "Former First Lady of the United States",
        "Wisdom",
    ),
    (
        "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
        "Eleanor Roosevelt",
        "Former First Lady of the United States",
        "People",
    ),
    (
        "Do what you feel in your heart to be right - for you"
        "ll be criticized anyway.",
        "Eleanor Roosevelt",
        "Former First Lady of the United States",
        "Wisdom",
    ),
    (
        "Do what you feel in your heart to be right - for you"
        "ll be criticized anyway.",
        "Eleanor Roosevelt",
        "Former First Lady of the United States",
        "Advice",
    ),
    (
        "Do one thing every day that scares you.",
        "Eleanor Roosevelt",
        "Former First Lady of the United States",
        "Wisdom",
    ),
    (
        "Do one thing every day that scares you.",
        "Eleanor Roosevelt",
        "Former First Lady of the United States",
        "Life",
    ),
    (
        "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate; only love can do that.",
        "Martin Luther King",
        "American minister",
        "Inspirational",
    ),
    (
        "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate; only love can do that.",
        "Martin Luther King",
        "American minister",
        "Wisdom",
    ),
    (
        "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate; only love can do that.",
        "Martin Luther King",
        "American minister",
        "Love",
    ),
    (
        "Our lives begin to end the day we become silent about things that matter.",
        "Martin Luther King",
        "American minister",
        "Inspirational",
    ),
    (
        "Our lives begin to end the day we become silent about things that matter.",
        "Martin Luther King",
        "American minister",
        "Life",
    ),
    (
        "In the end, we will remember not the words of our enemies, but the silence of our friends.",
        "Martin Luther King",
        "American minister",
        "People",
    ),
    (
        "In the end, we will remember not the words of our enemies, but the silence of our friends.",
        "Martin Luther King",
        "American minister",
        "Life",
    ),
    (
        "Injustice anywhere is a threat to justice everywhere.",
        "Martin Luther King",
        "American minister",
        "Wisdom",
    ),
    (
        "The time is always right to do what is right.",
        "Martin Luther King",
        "American minister",
        "Inspirational",
    ),
    (
        "The time is always right to do what is right.",
        "Martin Luther King",
        "American minister",
        "Wisdom",
    ),
    (
        "Life"
        "s most persistent and urgent question is, "
        "What are you doing for others?",
        "Martin Luther King",
        "American minister",
        "Inspirational",
    ),
    (
        "Life"
        "s most persistent and urgent question is, "
        "What are you doing for others?",
        "Martin Luther King",
        "American minister",
        "Life",
    ),
    (
        "Life"
        "s most persistent and urgent question is, "
        "What are you doing for others?",
        "Martin Luther King",
        "American minister",
        "People",
    ),
    (
        "Weak people revenge. Strong people forgive. Intelligent People Ignore.",
        "Albert Einstein",
        "Theoretical physicist",
        "Inspirational",
    ),
    (
        "Weak people revenge. Strong people forgive. Intelligent People Ignore.",
        "Albert Einstein",
        "Theoretical physicist",
        "Life",
    ),
    (
        "I have not failed. I" "ve just found 10,000 ways that won" "t work.",
        "Thomas A. Edison",
        "American inventor",
        "Inspirational",
    ),
    (
        "Genius is one percent inspiration and ninety-nine percent perspiration.",
        "Thomas A. Edison",
        "American inventor",
        "Inspirational",
    ),
    (
        "Genius is one percent inspiration and ninety-nine percent perspiration.",
        "Thomas A. Edison",
        "American inventor",
        "Wisdom",
    ),
    (
        "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.",
        "Thomas A. Edison",
        "American inventor",
        "Inspirational",
    ),
    (
        "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.",
        "Thomas A. Edison",
        "American inventor",
        "Advice",
    ),
    (
        "If we did all the things we are capable of, we would literally astound ourselves.",
        "Thomas A. Edison",
        "American inventor",
        "Inspirational",
    ),
    (
        "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.",
        "Albert Einstein",
        "Theoretical physicist",
        "Inspirational",
    ),
    (
        "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.",
        "Albert Einstein",
        "Theoretical physicist",
        "Wisdom",
    ),
    (
        "Life isn" "t about finding yourself. Life is about creating yourself.",
        "George Bernard Shaw",
        "Irish playwright",
        "Inspirational",
    ),
    (
        "Life isn" "t about finding yourself. Life is about creating yourself.",
        "George Bernard Shaw",
        "Irish playwright",
        "Life",
    ),
    (
        "Life isn" "t about finding yourself. Life is about creating yourself.",
        "George Bernard Shaw",
        "Irish playwright",
        "Advice",
    ),
    (
        "Success is not final, failure is not fatal: it is the courage to continue that counts.",
        "Winston Churchill",
        "Former British Prime Minister",
        "Inspirational",
    ),
    (
        "Success is not final, failure is not fatal: it is the courage to continue that counts.",
        "Winston Churchill",
        "Former British Prime Minister",
        "Life",
    ),
    (
        "Success is not final, failure is not fatal: it is the courage to continue that counts.",
        "Winston Churchill",
        "Former British Prime Minister",
        "Advice",
    ),
    (
        "If you" "re going through hell, keep going.",
        "Winston Churchill",
        "Former British Prime Minister",
        "Inspirational",
    ),
    (
        "If you" "re going through hell, keep going.",
        "Winston Churchill",
        "Former British Prime Minister",
        "Advice",
    ),
    (
        "We make a living by what we get, but we make a life by what we give.",
        "Winston Churchill",
        "Former British Prime Minister",
        "People",
    ),
    (
        "We make a living by what we get, but we make a life by what we give.",
        "Winston Churchill",
        "Former British Prime Minister",
        "Life",
    ),
    (
        "Peace begins with a smile.",
        "Mother Teresa",
        "Roman Catholic Saint",
        "Inspirational",
    ),
    ("Peace begins with a smile.", "Mother Teresa", "Roman Catholic Saint", "Wisdom"),
    (
        "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
        "Mother Teresa",
        "Roman Catholic Saint",
        "Inspirational",
    ),
    (
        "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
        "Mother Teresa",
        "Roman Catholic Saint",
        "Love",
    ),
    (
        "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
        "Mother Teresa",
        "Roman Catholic Saint",
        "Advice",
    ),
    (
        "If you can" "t feed a hundred people, then feed just one.",
        "Mother Teresa",
        "Roman Catholic Saint",
        "Inspirational",
    ),
    (
        "If you can" "t feed a hundred people, then feed just one.",
        "Mother Teresa",
        "Roman Catholic Saint",
        "Advice",
    ),
    (
        "If you can" "t feed a hundred people, then feed just one.",
        "Mother Teresa",
        "Roman Catholic Saint",
        "People",
    ),
    (
        "Kind words can be short and easy to speak, but their echoes are truly endless.",
        "Mother Teresa",
        "Roman Catholic Saint",
        "Inspirational",
    ),
    (
        "Kind words can be short and easy to speak, but their echoes are truly endless.",
        "Mother Teresa",
        "Roman Catholic Saint",
        "People",
    ),
    (
        "Isn"
        "t it nice to think that tomorrow is a new day with no mistakes in it yet?",
        "L.M. Montgomery",
        "Canadian author",
        "Inspirational",
    ),
    (
        "Tomorrow is always fresh, with no mistakes in it.",
        "L.M. Montgomery",
        "Canadian author",
        "Inspirational",
    ),
    (
        "We should regret our mistakes and learn from them, but never carry them forward into the future with us.",
        "L.M. Montgomery",
        "Canadian author",
        "Inspirational",
    ),
    (
        "We should regret our mistakes and learn from them, but never carry them forward into the future with us.",
        "L.M. Montgomery",
        "Canadian author",
        "Advice",
    ),
    (
        "We should regret our mistakes and learn from them, but never carry them forward into the future with us.",
        "L.M. Montgomery",
        "Canadian author",
        "Life",
    ),
    (
        "It" "s so easy to be wicked without knowing it, isn" "t it?",
        "L.M. Montgomery",
        "Canadian author",
        "Inspirational",
    ),
    (
        "It" "s so easy to be wicked without knowing it, isn" "t it?",
        "L.M. Montgomery",
        "Canadian author",
        "Philosophy",
    ),
    (
        "It" "s so easy to be wicked without knowing it, isn" "t it?",
        "L.M. Montgomery",
        "Canadian author",
        "Life",
    ),
    (
        "All the darkness in the world cannot extinguish the light of a single candle.",
        "Francis of Assisi",
        "Italian Catholic Saint",
        "Inspirational",
    ),
    (
        "All the darkness in the world cannot extinguish the light of a single candle.",
        "Francis of Assisi",
        "Italian Catholic Saint",
        "Wisdom",
    ),
    (
        "Start by doing what"
        "s necessary; then do what"
        "s possible; and suddenly you are doing the impossible.",
        "Francis of Assisi",
        "Italian Catholic Saint",
        "Inspirational",
    ),
    (
        "Start by doing what"
        "s necessary; then do what"
        "s possible; and suddenly you are doing the impossible.",
        "Francis of Assisi",
        "Italian Catholic Saint",
        "Wisdom",
    ),
    (
        "Preach the Gospel at all times and when necessary use words.",
        "Francis of Assisi",
        "Italian Catholic Saint",
        "Religion",
    ),
    (
        "Preach the Gospel at all times and when necessary use words.",
        "Francis of Assisi",
        "Italian Catholic Saint",
        "Wisdom",
    ),
    (
        "A single sunbeam is enough to drive away many shadows.",
        "Francis of Assisi",
        "Italian Catholic Saint",
        "Inspirational",
    ),
    (
        "A single sunbeam is enough to drive away many shadows.",
        "Francis of Assisi",
        "Italian Catholic Saint",
        "Wisdom",
    ),
    (
        "You never fail until you stop trying.",
        "Albert Einstein",
        "Theoretical physicist",
        "Inspirational",
    ),
    (
        "You never fail until you stop trying.",
        "Albert Einstein",
        "Theoretical physicist",
        "Advice",
    ),
    (
        "You see things; you say, "
        "Why?"
        " But I dream things that never were; and I say "
        "Why not?",
        "George Bernard Shaw",
        "Irish playwright",
        "Inspirational",
    ),
    (
        "We don"
        "t stop playing because we grow old; we grow old because we stop playing.",
        "George Bernard Shaw",
        "Irish playwright",
        "Inspirational",
    ),
    (
        "Progress is impossible without change, and those who cannot change their minds cannot change anything.",
        "George Bernard Shaw",
        "Irish playwright",
        "Inspirational",
    ),
    (
        "A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.",
        "George Bernard Shaw",
        "Irish playwright",
        "Inspirational",
    ),
    (
        "Kindness is a language which the deaf can hear and the blind can see.",
        "Mark Twain",
        "American writer",
        "Inspirational",
    ),
    (
        "The secret of getting ahead is getting started.",
        "Mark Twain",
        "American writer",
        "Inspirational",
    ),
    (
        "The secret of getting ahead is getting started.",
        "Mark Twain",
        "American writer",
        "Advice",
    ),
    (
        "Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
        "Mark Twain",
        "American writer",
        "Inspirational",
    ),
    (
        "Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
        "Mark Twain",
        "American writer",
        "Advice",
    ),
    (
        "The two most important days in your life are the day you are born and the day you find out why.",
        "Mark Twain",
        "American writer",
        "Inspirational",
    ),
    (
        "The two most important days in your life are the day you are born and the day you find out why.",
        "Mark Twain",
        "American writer",
        "Life",
    ),
    (
        "Truth is stranger than fiction, but it is because Fiction is obliged to stick to possibilities; Truth isn"
        "t.",
        "Mark Twain",
        "American writer",
        "Inspirational",
    ),
    (
        "Truth is stranger than fiction, but it is because Fiction is obliged to stick to possibilities; Truth isn"
        "t.",
        "Mark Twain",
        "American writer",
        "Life",
    ),
    (
        "If you tell the truth, you don" "t have to remember anything.",
        "Mark Twain",
        "American writer",
        "Inspirational",
    ),
    (
        "If you tell the truth, you don" "t have to remember anything.",
        "Mark Twain",
        "American writer",
        "Wisdom",
    ),
    (
        "I have never met a man so ignorant that I couldn" "t learn something from him",
        "Galileo Galilei",
        "Italian Polymath",
        "Inspirational",
    ),
    (
        "Earth provides enough to satisfy every man"
        "s needs, but not every man"
        "s greed.",
        "Mahatma Gandhi",
        "Indian leader",
        "Inspirational",
    ),
    (
        "Earth provides enough to satisfy every man"
        "s needs, but not every man"
        "s greed.",
        "Mahatma Gandhi",
        "Indian leader",
        "Wisdom",
    ),
    ("Where there is love there is life.", "Mahatma Gandhi", "Indian leader", "Life"),
    ("Where there is love there is life.", "Mahatma Gandhi", "Indian leader", "Love"),
    (
        "Happiness is when what you think, what you say, and what you do are in harmony.",
        "Mahatma Gandhi",
        "Indian leader",
        "Inspirational",
    ),
    (
        "Happiness is when what you think, what you say, and what you do are in harmony.",
        "Mahatma Gandhi",
        "Indian leader",
        "Wisdom",
    ),
    (
        "Happiness is when what you think, what you say, and what you do are in harmony.",
        "Mahatma Gandhi",
        "Indian leader",
        "Philosophy",
    ),
    (
        "The weak can never forgive. Forgiveness is the attribute of the strong.",
        "Mahatma Gandhi",
        "Indian leader",
        "Inspirational",
    ),
    (
        "The weak can never forgive. Forgiveness is the attribute of the strong.",
        "Mahatma Gandhi",
        "Indian leader",
        "Wisdom",
    ),
    (
        "The weak can never forgive. Forgiveness is the attribute of the strong.",
        "Mahatma Gandhi",
        "Indian leader",
        "Philosophy",
    ),
    (
        "Strength does not come from physical capacity. It comes from an indomitable will.",
        "Mahatma Gandhi",
        "Indian leader",
        "Inspirational",
    ),
    (
        "Strength does not come from physical capacity. It comes from an indomitable will.",
        "Mahatma Gandhi",
        "Indian leader",
        "Wisdom",
    ),
    (
        "Strength does not come from physical capacity. It comes from an indomitable will.",
        "Mahatma Gandhi",
        "Indian leader",
        "Philosophy",
    ),
    (
        "You must not lose faith in humanity. Humanity is an ocean; if a few drops of the ocean are dirty, the ocean does not become dirty.",
        "Mahatma Gandhi",
        "Indian leader",
        "Inspirational",
    ),
    (
        "You must not lose faith in humanity. Humanity is an ocean; if a few drops of the ocean are dirty, the ocean does not become dirty.",
        "Mahatma Gandhi",
        "Indian leader",
        "Wisdom",
    ),
    (
        "You must not lose faith in humanity. Humanity is an ocean; if a few drops of the ocean are dirty, the ocean does not become dirty.",
        "Mahatma Gandhi",
        "Indian leader",
        "Philosophy",
    ),
    (
        "In a gentle way, you can shake the world.",
        "Mahatma Gandhi",
        "Indian leader",
        "Inspirational",
    ),
    (
        "In a gentle way, you can shake the world.",
        "Mahatma Gandhi",
        "Indian leader",
        "Wisdom",
    ),
    (
        "In a gentle way, you can shake the world.",
        "Mahatma Gandhi",
        "Indian leader",
        "Philosophy",
    ),
    (
        "He that can have patience can have what he will.",
        "Benjamin Franklin",
        "Founding Father of the United States",
        "Inspirational",
    ),
    (
        "He that can have patience can have what he will.",
        "Benjamin Franklin",
        "Founding Father of the United States",
        "Wisdom",
    ),
    (
        "Either write something worth reading or do something worth writing.",
        "Benjamin Franklin",
        "Founding Father of the United States",
        "Inspirational",
    ),
    (
        "Either write something worth reading or do something worth writing.",
        "Benjamin Franklin",
        "Founding Father of the United States",
        "Advice",
    ),
    (
        "Tell me and I forget, teach me and I may remember, involve me and I learn.",
        "Benjamin Franklin",
        "Founding Father of the United States",
        "Inspirational",
    ),
    (
        "Tell me and I forget, teach me and I may remember, involve me and I learn.",
        "Benjamin Franklin",
        "Founding Father of the United States",
        "Wisdom",
    ),
    (
        "Tell me and I forget, teach me and I may remember, involve me and I learn.",
        "Benjamin Franklin",
        "Founding Father of the United States",
        "Philosophy",
    ),
    (
        "Never ruin an apology with an excuse.",
        "Benjamin Franklin",
        "Founding Father of the United States",
        "Life",
    ),
    (
        "Never ruin an apology with an excuse.",
        "Benjamin Franklin",
        "Founding Father of the United States",
        "Advice",
    ),
    (
        "Early to bed and early to rise makes a man healthy, wealthy and wise.",
        "Benjamin Franklin",
        "Founding Father of the United States",
        "Life",
    ),
    (
        "Early to bed and early to rise makes a man healthy, wealthy and wise.",
        "Benjamin Franklin",
        "Founding Father of the United States",
        "Advice",
    ),
    (
        "By failing to prepare, you are preparing to fail.",
        "Benjamin Franklin",
        "Founding Father of the United States",
        "Inspirational",
    ),
    (
        "By failing to prepare, you are preparing to fail.",
        "Benjamin Franklin",
        "Founding Father of the United States",
        "Advice",
    ),
    (
        "Those who look for the bad in people will surely find it.",
        "Abraham Lincoln",
        "16th U.S. President",
        "Inspirational",
    ),
    (
        "Those who look for the bad in people will surely find it.",
        "Abraham Lincoln",
        "16th U.S. President",
        "People",
    ),
    (
        "People don" "t realize how a man" "s whole life can be changed by one book.",
        "Malcolm X",
        "American minister",
        "Inspirational",
    ),
    (
        "People don" "t realize how a man" "s whole life can be changed by one book.",
        "Malcolm X",
        "American minister",
        "Life",
    ),
    (
        "If you have no critics you" "ll likely have no success.",
        "Malcolm X",
        "American minister",
        "Inspirational",
    ),
    (
        "If you have no critics you" "ll likely have no success.",
        "Malcolm X",
        "American minister",
        "Wisdom",
    ),
    (
        "I"
        "m for truth, no matter who tells it. I"
        "m for justice, no matter who it"
        "s for or against.",
        "Malcolm X",
        "American minister",
        "Inspirational",
    ),
    (
        "I"
        "m for truth, no matter who tells it. I"
        "m for justice, no matter who it"
        "s for or against.",
        "Malcolm X",
        "American minister",
        "Wisdom",
    ),
    (
        "It is not a lack of Love, but a lack of People that makes unhappy marriages.",
        "Friedrich Nietzsche",
        "German philosopher",
        "Love",
    ),
    (
        "It is not a lack of Love, but a lack of People that makes unhappy marriages.",
        "Friedrich Nietzsche",
        "German philosopher",
        "Marriage",
    ),
    (
        "He who has a why to live can bear almost any how.",
        "Friedrich Nietzsche",
        "German philosopher",
        "Life",
    ),
    (
        "He who has a why to live can bear almost any how.",
        "Friedrich Nietzsche",
        "German philosopher",
        "Inspirational",
    ),
    (
        "That which does not kill us makes us stronger",
        "Friedrich Nietzsche",
        "German philosopher",
        "Inspirational",
    ),
    (
        "That which does not kill us makes us stronger",
        "Friedrich Nietzsche",
        "German philosopher",
        "Philosophy",
    ),
    (
        "To live is to suffer, to survive is to find some meaning in the suffering.",
        "Friedrich Nietzsche",
        "German philosopher",
        "Life",
    ),
    (
        "To live is to suffer, to survive is to find some meaning in the suffering.",
        "Friedrich Nietzsche",
        "German philosopher",
        "Philosophy",
    ),
    (
        "To live is to suffer, to survive is to find some meaning in the suffering.",
        "Friedrich Nietzsche",
        "German philosopher",
        "Inspirational",
    ),
    (
        "There is always some madness in love. But there is also always some reason in madness.",
        "Friedrich Nietzsche",
        "German philosopher",
        "Philosophy",
    ),
    (
        "There is always some madness in love. But there is also always some reason in madness.",
        "Friedrich Nietzsche",
        "German philosopher",
        "Love",
    ),
    (
        "No price is too high to pay for the privilege of owning yourself.",
        "Friedrich Nietzsche",
        "German philosopher",
        "Philosophy",
    ),
    (
        "No price is too high to pay for the privilege of owning yourself.",
        "Friedrich Nietzsche",
        "German philosopher",
        "Advice",
    ),
    (
        "You know, when it works, Love is amazing. It" "s not overrated.",
        "Sarah Dessen",
        "American novelist",
        "Love",
    ),
    (
        "You know, when it works, Love is amazing. It" "s not overrated.",
        "Sarah Dessen",
        "American novelist",
        "Life",
    ),
    (
        "Life is an awful, ugly place to not have a best friend.",
        "Sarah Dessen",
        "American novelist",
        "Friends",
    ),
    (
        "Life is an awful, ugly place to not have a best friend.",
        "Sarah Dessen",
        "American novelist",
        "Life",
    ),
    (
        "There is never a time or place for true love. It happens accidentally, in a heartbeat, in a single flashing, throbbing moment.",
        "Sarah Dessen",
        "American novelist",
        "Love",
    ),
    (
        "There is never a time or place for true love. It happens accidentally, in a heartbeat, in a single flashing, throbbing moment.",
        "Sarah Dessen",
        "American novelist",
        "Life",
    ),
    (
        "Anyone can hide. Facing up to things, working through them, that"
        "s what makes you strong.",
        "Sarah Dessen",
        "American novelist",
        "Love",
    ),
    (
        "Anyone can hide. Facing up to things, working through them, that"
        "s what makes you strong.",
        "Sarah Dessen",
        "American novelist",
        "Life",
    ),
    (
        "If you want to live a happy life, tie it to a goal, not to people or things",
        "Albert Einstein",
        "Theoretical physicist",
        "Inspirational",
    ),
    (
        "If you want to live a happy life, tie it to a goal, not to people or things",
        "Albert Einstein",
        "Theoretical physicist",
        "Life",
    ),
    (
        "Your time is limited, so don’t waste it living someone else’s life.",
        "Steve Jobs",
        "American entrepreneur",
        "Inspirational",
    ),
    (
        "Your time is limited, so don’t waste it living someone else’s life.",
        "Steve Jobs",
        "American entrepreneur",
        "Life",
    ),
    (
        "Your time is limited, so don’t waste it living someone else’s life.",
        "Steve Jobs",
        "American entrepreneur",
        "Advice",
    ),
    (
        "Everything around you that you call life was made up by people, and you can change it.",
        "Steve Jobs",
        "American entrepreneur",
        "Inspirational",
    ),
    (
        "Everything around you that you call life was made up by people, and you can change it.",
        "Steve Jobs",
        "American entrepreneur",
        "Life",
    ),
    (
        "Everything around you that you call life was made up by people, and you can change it.",
        "Steve Jobs",
        "American entrepreneur",
        "People",
    ),
    (
        "Design is not just what it looks like and feels like. Design is how it works.",
        "Steve Jobs",
        "American entrepreneur",
        "Inspirational",
    ),
    (
        "Design is not just what it looks like and feels like. Design is how it works.",
        "Steve Jobs",
        "American entrepreneur",
        "Design",
    ),
    (
        "Innovation distinguishes between a leader and a follower.",
        "Steve Jobs",
        "American entrepreneur",
        "Inspirational",
    ),
    (
        "Innovation distinguishes between a leader and a follower.",
        "Steve Jobs",
        "American entrepreneur",
        "Philosophy",
    ),
    (
        "Sometimes life is going to hit you in the head with a brick. Don"
        "t lose faith.",
        "Steve Jobs",
        "American entrepreneur",
        "Faith",
    ),
    (
        "Sometimes life is going to hit you in the head with a brick. Don"
        "t lose faith.",
        "Steve Jobs",
        "American entrepreneur",
        "Advice",
    ),
    (
        "Sometimes life is going to hit you in the head with a brick. Don"
        "t lose faith.",
        "Steve Jobs",
        "American entrepreneur",
        "Life",
    ),
    (
        "Sometimes when you innovate, you make mistakes. It is best to admit them quickly, and get on with improving your other innovations.",
        "Steve Jobs",
        "American entrepreneur",
        "Innovation",
    ),
    (
        "Sometimes when you innovate, you make mistakes. It is best to admit them quickly, and get on with improving your other innovations.",
        "Steve Jobs",
        "American entrepreneur",
        "Advice",
    ),
    (
        "A lot of times, people don" "t know what they want until you show it to them.",
        "Steve Jobs",
        "American entrepreneur",
        "People",
    ),
    (
        "A lot of times, people don" "t know what they want until you show it to them.",
        "Steve Jobs",
        "American entrepreneur",
        "Philosophy",
    ),
    (
        "Let’s go invent tomorrow rather than worrying about what happened yesterday.",
        "Steve Jobs",
        "American entrepreneur",
        "Innovation",
    ),
    (
        "Let’s go invent tomorrow rather than worrying about what happened yesterday.",
        "Steve Jobs",
        "American entrepreneur",
        "Inspirational",
    ),
    (
        "The most precious thing that we all have with us is time.",
        "Steve Jobs",
        "American entrepreneur",
        "Inspirational",
    ),
    (
        "The most precious thing that we all have with us is time.",
        "Steve Jobs",
        "American entrepreneur",
        "Wisdom",
    ),
    (
        "You have to trust in something, your gut, destiny, life, karma, whatever.",
        "Steve Jobs",
        "American entrepreneur",
        "Inspirational",
    ),
    (
        "You have to trust in something, your gut, destiny, life, karma, whatever.",
        "Steve Jobs",
        "American entrepreneur",
        "Life",
    ),
    (
        "You have to trust in something, your gut, destiny, life, karma, whatever.",
        "Steve Jobs",
        "American entrepreneur",
        "Faith",
    ),
    (
        "Every child is an artist, the problem is staying an artist when you grow up.",
        "Pablo Picasso",
        "Spanish painter",
        "Art",
    ),
    (
        "Every child is an artist, the problem is staying an artist when you grow up.",
        "Pablo Picasso",
        "Spanish painter",
        "Life",
    ),
    (
        "The purpose of art is washing the dust of daily life off our souls.",
        "Pablo Picasso",
        "Spanish painter",
        "Art",
    ),
    (
        "The purpose of art is washing the dust of daily life off our souls.",
        "Pablo Picasso",
        "Spanish painter",
        "Life",
    ),
    (
        "Good artists copy, great artists steal.",
        "Pablo Picasso",
        "Spanish painter",
        "Art",
    ),
    (
        "Art is a lie that makes us realize truth.",
        "Pablo Picasso",
        "Spanish painter",
        "Art",
    ),
    (
        "Inspiration does exist, but it must find you working.",
        "Pablo Picasso",
        "Spanish painter",
        "Art",
    ),
    (
        "Inspiration does exist, but it must find you working.",
        "Pablo Picasso",
        "Spanish painter",
        "Advice",
    ),
    (
        "Inspiration does exist, but it must find you working.",
        "Pablo Picasso",
        "Spanish painter",
        "Inspirational",
    ),
    (
        "Strive not to be a success, but rather to be of value.",
        "Albert Einstein",
        "Theoretical physicist",
        "Inspirational",
    ),
    (
        "Strive not to be a success, but rather to be of value.",
        "Albert Einstein",
        "Theoretical physicist",
        "Life",
    ),
    (
        "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",
        "Winston Churchill",
        "Former British Prime Minister",
        "Inspirational",
    ),
    (
        "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",
        "Winston Churchill",
        "Former British Prime Minister",
        "Life",
    ),
    (
        "We learn wisdom from failure much more than from success.",
        "Samuel Smiles",
        "Scottish Author",
        "Inspirational",
    ),
    (
        "We learn wisdom from failure much more than from success.",
        "Samuel Smiles",
        "Scottish Author",
        "Wisdom",
    ),
    (
        "We learn wisdom from failure much more than from success.",
        "Samuel Smiles",
        "Scottish Author",
        "Failure",
    ),
    (
        "We learn wisdom from failure much more than from success.",
        "Samuel Smiles",
        "Scottish Author",
        "Success",
    ),
    (
        "Hope is like the sun, which, as we journey toward it, casts the shadow of our burden behind us.",
        "Samuel Smiles",
        "Scottish Author",
        "Inspirational",
    ),
    (
        "Hope is like the sun, which, as we journey toward it, casts the shadow of our burden behind us.",
        "Samuel Smiles",
        "Scottish Author",
        "Wisdom",
    ),
    (
        "We often discover what will do, by finding out what will not do; and probably he who never made a mistake never made a discovery.",
        "Samuel Smiles",
        "Scottish Author",
        "Inspirational",
    ),
    (
        "We often discover what will do, by finding out what will not do; and probably he who never made a mistake never made a discovery.",
        "Samuel Smiles",
        "Scottish Author",
        "Wisdom",
    ),
    (
        "We often discover what will do, by finding out what will not do; and probably he who never made a mistake never made a discovery.",
        "Samuel Smiles",
        "Scottish Author",
        "Failure",
    ),
    (
        "Lost wealth may be replaced by industry, lost knowledge by study, lost health by temperance or medicine, but lost time is gone forever.",
        "Samuel Smiles",
        "Scottish Author",
        "Inspirational",
    ),
    (
        "Lost wealth may be replaced by industry, lost knowledge by study, lost health by temperance or medicine, but lost time is gone forever.",
        "Samuel Smiles",
        "Scottish Author",
        "Wisdom",
    ),
    (
        "Lost wealth may be replaced by industry, lost knowledge by study, lost health by temperance or medicine, but lost time is gone forever.",
        "Samuel Smiles",
        "Scottish Author",
        "Time",
    ),
    (
        "Life will always be to a large extent what we ourselves make it.",
        "Samuel Smiles",
        "Scottish Author",
        "Inspirational",
    ),
    (
        "Life will always be to a large extent what we ourselves make it.",
        "Samuel Smiles",
        "Scottish Author",
        "Life",
    ),
    (
        "Enthusiasm... the sustaining power of all great action.",
        "Samuel Smiles",
        "Scottish Author",
        "Inspirational",
    ),
    (
        "Enthusiasm... the sustaining power of all great action.",
        "Samuel Smiles",
        "Scottish Author",
        "Life",
    ),
    (
        "People who are crazy enough to think they can change the world, are the ones who do.",
        "Winston Churchill",
        "Former British Prime Minister",
        "Inspirational",
    ),
    (
        "People who are crazy enough to think they can change the world, are the ones who do.",
        "Winston Churchill",
        "Former British Prime Minister",
        "Life",
    ),
    (
        "People who are crazy enough to think they can change the world, are the ones who do.",
        "Winston Churchill",
        "Former British Prime Minister",
        "People",
    ),
    (
        "The fool doth think he is wise, but the wise man knows himself to be a fool.",
        "William Shakespeare",
        "English poet",
        "Wisdom",
    ),
    (
        "There is nothing either good or bad, but thinking makes it so.",
        "William Shakespeare",
        "English poet",
        "Philosophy",
    ),
    (
        "You"
        "re not to be so blind with patriotism that you can"
        "t face reality. Wrong is wrong, no matter who does it or says it.",
        "Malcolm X",
        "American minister",
        "Philosophy",
    ),
    (
        "Hell is empty and all the devils are here.",
        "William Shakespeare",
        "English poet",
        "Philosophy",
    ),
    (
        "The course of true Love never did run smooth.",
        "William Shakespeare",
        "English poet",
        "Love",
    ),
    (
        "The course of true Love never did run smooth.",
        "William Shakespeare",
        "English poet",
        "Wisdom",
    ),
    (
        "Expectation is the root of all heartache.",
        "William Shakespeare",
        "English poet",
        "Philosophy",
    ),
    (
        "Expectation is the root of all heartache.",
        "William Shakespeare",
        "English poet",
        "Wisdom",
    ),
    (
        "Listen to many, speak to a few.",
        "William Shakespeare",
        "English poet",
        "Wisdom",
    ),
    (
        "Listen to many, speak to a few.",
        "William Shakespeare",
        "English poet",
        "Inspirational",
    ),
    (
        "One may smile, and smile, and be a villain.",
        "William Shakespeare",
        "English poet",
        "Philosophy",
    ),
    (
        "One may smile, and smile, and be a villain.",
        "William Shakespeare",
        "English poet",
        "Wisdom",
    ),
    (
        "Any fool can know. The point is to understand.",
        "Albert Einstein",
        "Theoretical physicist",
        "Philosophy",
    ),
    (
        "Any fool can know. The point is to understand.",
        "Albert Einstein",
        "Theoretical physicist",
        "Wisdom",
    ),
    (
        "Any fool can know. The point is to understand.",
        "Albert Einstein",
        "Theoretical physicist",
        "Inspirational",
    ),
    (
        "It is not that I" "m so smart. But I stay with the questions much longer.",
        "Albert Einstein",
        "Theoretical physicist",
        "Philosophy",
    ),
    (
        "It is not that I" "m so smart. But I stay with the questions much longer.",
        "Albert Einstein",
        "Theoretical physicist",
        "Wisdom",
    ),
    (
        "It is not that I" "m so smart. But I stay with the questions much longer.",
        "Albert Einstein",
        "Theoretical physicist",
        "Inspirational",
    ),
    (
        "Build your own dreams, or someone else will hire you to build theirs.",
        "Farrah Gray",
        "American businessman",
        "Wisdom",
    ),
    (
        "Build your own dreams, or someone else will hire you to build theirs.",
        "Farrah Gray",
        "American businessman",
        "Inspirational",
    ),
    (
        "Build your own dreams, or someone else will hire you to build theirs.",
        "Farrah Gray",
        "American businessman",
        "Dream",
    ),
    (
        "Comfort is the enemy of achievement",
        "Farrah Gray",
        "American businessman",
        "Achievement",
    ),
    (
        "Comfort is the enemy of achievement",
        "Farrah Gray",
        "American businessman",
        "Inspirational",
    ),
    (
        "You know, you don" "t have to have money to be a successful businessperson.",
        "Farrah Gray",
        "American businessman",
        "Business",
    ),
    (
        "You know, you don" "t have to have money to be a successful businessperson.",
        "Farrah Gray",
        "American businessman",
        "Inspirational",
    ),
    (
        "I can dream alone and strive alone, but true success always requires the help and support of others.",
        "Farrah Gray",
        "American businessman",
        "People",
    ),
    (
        "I can dream alone and strive alone, but true success always requires the help and support of others.",
        "Farrah Gray",
        "American businessman",
        "Success",
    ),
    (
        "I can dream alone and strive alone, but true success always requires the help and support of others.",
        "Farrah Gray",
        "American businessman",
        "Dream",
    ),
    (
        "Success isn’t something that happens overnight: it’s a process.",
        "Farrah Gray",
        "American businessman",
        "Business",
    ),
    (
        "Success isn’t something that happens overnight: it’s a process.",
        "Farrah Gray",
        "American businessman",
        "Inspirational",
    ),
    (
        "Success isn’t something that happens overnight: it’s a process.",
        "Farrah Gray",
        "American businessman",
        "Success",
    ),
    (
        "The more we give, the more we receive. It"
        "s important to give back, because the seeds you plant today, you will harvest tomorrow.",
        "Farrah Gray",
        "American businessman",
        "Giving",
    ),
    (
        "Either you run the day, or the day runs you.",
        "Jim Rohn",
        "American entrepreneur",
        "Philosophy",
    ),
    (
        "Either you run the day, or the day runs you.",
        "Jim Rohn",
        "American entrepreneur",
        "Inspirational",
    ),
    (
        "Start from wherever you are and with whatever you’ve got.",
        "Jim Rohn",
        "American entrepreneur",
        "Advice",
    ),
    (
        "Start from wherever you are and with whatever you’ve got.",
        "Jim Rohn",
        "American entrepreneur",
        "Motivational",
    ),
    (
        "Without constant activity, the threats of life will soon overwhelm the values",
        "Jim Rohn",
        "American entrepreneur",
        "Life",
    ),
    (
        "Without constant activity, the threats of life will soon overwhelm the values",
        "Jim Rohn",
        "American entrepreneur",
        "Wisdom",
    ),
    (
        "If you don’t like how things are, change it! You’re not a tree.",
        "Jim Rohn",
        "American entrepreneur",
        "Motivational",
    ),
    (
        "If you don’t like how things are, change it! You’re not a tree.",
        "Jim Rohn",
        "American entrepreneur",
        "Wisdom",
    ),
    (
        "Success is neither magical nor mysterious. Success is the natural consequence of consistently applying basic fundamentals.",
        "Jim Rohn",
        "American entrepreneur",
        "Motivational",
    ),
    (
        "Success is neither magical nor mysterious. Success is the natural consequence of consistently applying basic fundamentals.",
        "Jim Rohn",
        "American entrepreneur",
        "Success",
    ),
    (
        "How long should you try? Until.",
        "Jim Rohn",
        "American entrepreneur",
        "Motivational",
    ),
    (
        "How long should you try? Until.",
        "Jim Rohn",
        "American entrepreneur",
        "Inspirational",
    ),
    (
        "Focus on making yourself better, not on thinking that you are better.",
        "Bohdi Sanders",
        "Author",
        "Inspirational",
    ),
    (
        "Focus on making yourself better, not on thinking that you are better.",
        "Bohdi Sanders",
        "Author",
        "Advice",
    ),
    (
        "A true friend is someone you can count on no matter what.",
        "Bohdi Sanders",
        "Author",
        "Friends",
    ),
    (
        "A true friend is someone you can count on no matter what.",
        "Bohdi Sanders",
        "Author",
        "Wisdom",
    ),
    (
        "Face your fears and you will be able to conquer them.",
        "Bohdi Sanders",
        "Author",
        "Fear",
    ),
    (
        "Face your fears and you will be able to conquer them.",
        "Bohdi Sanders",
        "Author",
        "Advice",
    ),
    (
        "If you want to know what people believe, don’t read what they write, don’t ask what they believe, just observe what they do.",
        "Bohdi Sanders",
        "Author",
        "People",
    ),
    (
        "If you want to know what people believe, don’t read what they write, don’t ask what they believe, just observe what they do.",
        "Bohdi Sanders",
        "Author",
        "Inspirational",
    ),
    (
        "I used to think I was indecisive, but now I am not quite sure.",
        "Tommy Cooper",
        "British Comedian",
        "Humor",
    ),
    (
        "Police arrested two kids yesterday, one was drinking battery acid, the other was eating fireworks. They charged one and let the other one off.",
        "Tommy Cooper",
        "British Comedian",
        "Humor",
    ),
    (
        "You know, somebody actually complimented me on my driving today. They left a little note on the windscreen, it said "
        "Parking Fine."
        "",
        "Tommy Cooper",
        "British Comedian",
        "Humor",
    ),
    (
        "A lie gets halfway around the world before the truth has a chance to get its pants on.",
        "Winston Churchill",
        "Former British Prime Minister",
        "Humor",
    ),
    (
        "A lie gets halfway around the world before the truth has a chance to get its pants on.",
        "Winston Churchill",
        "Former British Prime Minister",
        "Life",
    ),
    (
        "Knowledge is like underwear. It is useful to have it, but not necessary to show it off.",
        "Bill Murray",
        "American actor",
        "Humor",
    ),
    (
        "We are all here on earth to help others; what on earth the others are here for I don"
        "t know.",
        "Bill Murray",
        "American actor",
        "Humor",
    ),
    (
        "Happiness is having a large, loving, caring, close-knit family in another city.",
        "George Burns",
        "American comedian",
        "Humor",
    ),
    (
        "A professor is someone who talks in someone else" "s sleep.",
        "W. H. Auden",
        "English-American Poet",
        "Humor",
    ),
    (
        "Everything is changing. People are taking the comedians seriously and the politicians as a joke.",
        "Will Rogers",
        "American actor",
        "Humor",
    ),
    (
        "That’s why they call it the American Dream, because you have to be asleep to believe it.",
        "George Carlin",
        "American comedian",
        "Humor",
    ),
    (
        "If you’re too open-minded; your brains may fall out.",
        "Lawrence Ferlinghetti",
        "American poet",
        "Humor",
    ),
    (
        "If you think nobody cares about you, try missing a couple of payments.",
        "Steven Wright",
        "American stand-up comedian",
        "Humor",
    ),
    (
        "There"
        "s a fine line between fishing and just standing on the shore like an idiot.",
        "Steven Wright",
        "American stand-up comedian",
        "Humor",
    ),
    (
        "If at first you don" "t succeed then skydiving definitely isn" "t for you.",
        "Steven Wright",
        "American stand-up comedian",
        "Humor",
    ),
    (
        "A lot of people are afraid of heights. Not me, I" "m afraid of widths.",
        "Steven Wright",
        "American stand-up comedian",
        "Humor",
    ),
    (
        "What" "s another word for Thesaurus?",
        "Steven Wright",
        "American stand-up comedian",
        "Humor",
    ),
    (
        "You can" "t have everything. Where would you put it?",
        "Steven Wright",
        "American stand-up comedian",
        "Humor",
    ),
    (
        "Don’t be so humble – you are not that great.",
        "Golda Meir",
        "Former Prime Minister of Israel",
        "Humor",
    ),
    (
        "Whether women are better than men I cannot say - but I can say they are certainly no worse.",
        "Golda Meir",
        "Former Prime Minister of Israel",
        "Humor",
    ),
    (
        "The best way to teach your kids about taxes is by eating 30 percent of their ice cream.",
        "Bill Murray",
        "American actor",
        "Humor",
    ),
    (
        "You can" "t soar with the eagles as long as you hang out with the turkeys.",
        "Joel Osteen",
        "American televangelist",
        "Philosophy",
    ),
    (
        "You can" "t soar with the eagles as long as you hang out with the turkeys.",
        "Joel Osteen",
        "American televangelist",
        "Inspirational",
    ),
    (
        "You can change your world by changing your words... Remember, death and life are in the power of the tongue.",
        "Joel Osteen",
        "American televangelist",
        "Philosophy",
    ),
    (
        "You can change your world by changing your words... Remember, death and life are in the power of the tongue.",
        "Joel Osteen",
        "American televangelist",
        "Life",
    ),
    (
        "Nothing is impossible, the word itself says " "I" "m possible" "!",
        "Audrey Hepburn",
        "British actress",
        "Humor",
    ),
    (
        "Nothing is impossible, the word itself says " "I" "m possible" "!",
        "Audrey Hepburn",
        "British actress",
        "Inspirational",
    ),
    (
        "As you grow older, you will discover that you have two hands, one for helping yourself, the other for helping others.",
        "Audrey Hepburn",
        "British actress",
        "People",
    ),
    (
        "As you grow older, you will discover that you have two hands, one for helping yourself, the other for helping others.",
        "Audrey Hepburn",
        "British actress",
        "Inspirational",
    ),
    (
        "I never think of myself as an icon. What is in other people"
        "s minds is not in my mind. I just do my thing.",
        "Audrey Hepburn",
        "British actress",
        "People",
    ),
    (
        "I never think of myself as an icon. What is in other people"
        "s minds is not in my mind. I just do my thing.",
        "Audrey Hepburn",
        "British actress",
        "Inspirational",
    ),
    (
        "The best thing to hold onto in life is each other.",
        "Audrey Hepburn",
        "British actress",
        "People",
    ),
    (
        "The best thing to hold onto in life is each other.",
        "Audrey Hepburn",
        "British actress",
        "Life",
    ),
    (
        "Be nice to nerds. Chances are you" "ll end up working for one.",
        "Bill Gates",
        "American business magnate",
        "Humor",
    ),
    (
        "Be nice to nerds. Chances are you" "ll end up working for one.",
        "Bill Gates",
        "American business magnate",
        "Advice",
    ),
    (
        "Your most unhappy customers are your greatest source of learning.",
        "Bill Gates",
        "American business magnate",
        "Inspirational",
    ),
    (
        "Your most unhappy customers are your greatest source of learning.",
        "Bill Gates",
        "American business magnate",
        "People",
    ),
    (
        "Success is a lousy teacher. It seduces smart people into thinking they can"
        "t lose.",
        "Bill Gates",
        "American business magnate",
        "Inspirational",
    ),
    (
        "Success is a lousy teacher. It seduces smart people into thinking they can"
        "t lose.",
        "Bill Gates",
        "American business magnate",
        "People",
    ),
    (
        "Life is not fair; get used to it.",
        "Bill Gates",
        "American business magnate",
        "Inspirational",
    ),
    (
        "Life is not fair; get used to it.",
        "Bill Gates",
        "American business magnate",
        "Wisdom",
    ),
    (
        "If you can" "t make it good, at least make it look good.",
        "Bill Gates",
        "American business magnate",
        "Inspirational",
    ),
    (
        "If you can" "t make it good, at least make it look good.",
        "Bill Gates",
        "American business magnate",
        "Wisdom",
    ),
    (
        "If you can" "t make it good, at least make it look good.",
        "Bill Gates",
        "American business magnate",
        "Advice",
    ),
    (
        "Life is like riding a bicycle. To keep your balance, you must keep moving.",
        "Albert Einstein",
        "Theoretical physicist",
        "Life",
    ),
    (
        "Life is like riding a bicycle. To keep your balance, you must keep moving.",
        "Albert Einstein",
        "Theoretical physicist",
        "Inspirational",
    ),
    (
        "Nearly all men can stand adversity, but if you want to test a man’s character, give him power.",
        "Abraham Lincoln",
        "16th U.S. President",
        "Philosophy",
    ),
    (
        "Nearly all men can stand adversity, but if you want to test a man’s character, give him power.",
        "Abraham Lincoln",
        "16th U.S. President",
        "Wisdom",
    ),
    (
        "The best way to predict your future is to create it.",
        "Abraham Lincoln",
        "16th U.S. President",
        "Life",
    ),
    (
        "The best way to predict your future is to create it.",
        "Abraham Lincoln",
        "16th U.S. President",
        "Philosophy",
    ),
    (
        "The best way to predict your future is to create it.",
        "Abraham Lincoln",
        "16th U.S. President",
        "Wisdom",
    ),
    (
        "I would rather be a little nobody, then to be a evil somebody.",
        "Abraham Lincoln",
        "16th U.S. President",
        "Philosophy",
    ),
    (
        "I would rather be a little nobody, then to be a evil somebody.",
        "Abraham Lincoln",
        "16th U.S. President",
        "Wisdom",
    ),
    (
        "I will prepare and some day my chance will come.",
        "Abraham Lincoln",
        "16th U.S. President",
        "Inspirational",
    ),
    (
        "I will prepare and some day my chance will come.",
        "Abraham Lincoln",
        "16th U.S. President",
        "Life",
    ),
    (
        "Important principles may, and must, be inflexible.",
        "Abraham Lincoln",
        "16th U.S. President",
        "Philosophy",
    ),
    (
        "Important principles may, and must, be inflexible.",
        "Abraham Lincoln",
        "16th U.S. President",
        "Wisdom",
    ),
    (
        "Important principles may, and must, be inflexible.",
        "Abraham Lincoln",
        "16th U.S. President",
        "Inspirational",
    ),
    (
        "Tact is the ability to describe others as they see themselves.",
        "Abraham Lincoln",
        "16th U.S. President",
        "Philosophy",
    ),
    (
        "Tact is the ability to describe others as they see themselves.",
        "Abraham Lincoln",
        "16th U.S. President",
        "Wisdom",
    ),
    (
        "You cannot escape the responsibility of tomorrow by evading it today.",
        "Abraham Lincoln",
        "16th U.S. President",
        "Inspirational",
    ),
    (
        "You cannot escape the responsibility of tomorrow by evading it today.",
        "Abraham Lincoln",
        "16th U.S. President",
        "Philosophy",
    ),
    (
        "You cannot escape the responsibility of tomorrow by evading it today.",
        "Abraham Lincoln",
        "16th U.S. President",
        "Wisdom",
    ),
    (
        "Knowing thyself, that is the greatest wisdom.",
        "Galileo Galilei",
        "Italian Polymath",
        "Inspirational",
    ),
    (
        "Knowing thyself, that is the greatest wisdom.",
        "Galileo Galilei",
        "Italian Polymath",
        "Wisdom",
    ),
    (
        "To be humane, we must ever be ready to pronounce that wise, ingenious and modest statement "
        "I do not know"
        ".",
        "Galileo Galilei",
        "Italian Polymath",
        "Inspirational",
    ),
    (
        "To be humane, we must ever be ready to pronounce that wise, ingenious and modest statement "
        "I do not know"
        ".",
        "Galileo Galilei",
        "Italian Polymath",
        "Wisdom",
    ),
    (
        "Two truths cannot contradict one another.",
        "Galileo Galilei",
        "Italian Polymath",
        "Inspirational",
    ),
    (
        "Two truths cannot contradict one another.",
        "Galileo Galilei",
        "Italian Polymath",
        "Wisdom",
    ),
    (
        "Where the senses fail us, reason must step in.",
        "Galileo Galilei",
        "Italian Polymath",
        "Inspirational",
    ),
    (
        "Where the senses fail us, reason must step in.",
        "Galileo Galilei",
        "Italian Polymath",
        "Wisdom",
    ),
    (
        "All truths are easy to understand once they are discovered; the point is to discover them.",
        "Galileo Galilei",
        "Italian Polymath",
        "Inspirational",
    ),
    (
        "All truths are easy to understand once they are discovered; the point is to discover them.",
        "Galileo Galilei",
        "Italian Polymath",
        "Wisdom",
    ),
)
